### PR TITLE
Add primary keys for generator

### PR DESCRIPTION
**Pull request by arjunrn**
The following resources have ARNs which are set at the primary key:

- [PlatformEndpoint](https://docs.aws.amazon.com/sns/latest/api/API_GetEndpointAttributes.html)
- [PlatformApplication](https://docs.aws.amazon.com/sns/latest/api/API_GetPlatformApplicationAttributes.html)
- [Topic](https://docs.aws.amazon.com/sns/latest/api/API_GetTopicAttributes.html)
- [Subscription](https://docs.aws.amazon.com/sns/latest/api/API_GetSubscriptionAttributes.html)

Issue https://github.com/aws-controllers-k8s/community/issues/1778

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jaypipes — COMMENTED** [review]
@arjunrn I don't see any Go code changes after you changed the generator.yaml file, but I do see that you regenerated the controller (since the `apis/v1alpha1/ack-generate-metadata.yaml` file was updated). So... that tells me that adding these configurations to these fields in the generator.yaml file did not actually have any effect on the generated Go code. This could indicate that for these resources, the SetIdentifiers code path was already working fine by default and that adding the `is_arn_primary_key` configuration option is mostly just a documentation thing. Is that your understanding as well?

**Comment by arjunrn** [comment]
@jaypipes It's not changing anything right now because the version of the code generator I used is the one which is currently released and doesn't have the changes I added in https://github.com/aws-controllers-k8s/code-generator/pull/439 . In the current version of the code generator the set identifier is skipped. I added these fields so that when the bot updates the code generator there are no error during generation because the primary keys cannot be found. I can also update the generator version in this PR and run the generation again. But I assume that's not generally done.

**Comment by arjunrn** [comment]
@jaypipes Updated. There are some other changes from the generator as well.

**Review by jaypipes — APPROVED** [review]
:+1: thank you @arjunrn!

**Review by A-Hilaly — APPROVED** [review]
/lgtm

**Pull request merged**
