### PR TITLE
Fix subscription resource adoption

### PR DESCRIPTION
**Pull request by mustafasencer**
Issue [#1778](https://github.com/aws-controllers-k8s/community/issues/1778)

Description of changes:

Similar to previous errors; related to adoption of the `Subscription` resource. The `spec.protocol` field is a required_field.

```yaml
status:
  conditions:
  - message: 'Subscription.sns.services.k8s.aws "<SUBSCRIPTION_NAME>" is invalid: spec.protocol: Required value'
    status: "False"
    type: ACK.Adopted

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jaypipes — APPROVED** [review]
:+1: thank you! :)

**Comment by jaypipes** [comment]
@RedbackThomson can you take a look at this one please? I think there may be an issue adopting resources where there are required fields that are resource references.

If you look at the e2e failed test job, in the controller logs you will see this:

```
2023-05-31T16:21:13.293Z	ERROR	Reconciler error	{"controller": "subscription", "controllerGroup": "sns.services.k8s.aws", "controllerKind": "Subscription", "Subscription": {"name":"adopted-subscription-cfeu20i7ryz","namespace":"default"}, "namespace": "default", "name": "adopted-subscription-cfeu20i7ryz", "reconcileID": "6709364c-97d0-4c39-b83d-935fcf985b1d", "error": "resource reference wrapper or ID required: TopicARN,TopicRef"}
```

So it's almost like it's requiring adopted resources to have their references resolved *before* attempting to adopt them? Maybe? Your thoughts?

**Comment by mustafasencer** [comment]
I think the error originates from the fact that the following 2 fields: `Protocol`, `TopicARN` are required for the AWS sdk during the `subscribe` call. The `Endpoint` field on the other hand is neither required nor an attribute but rather a separate field for the `subscribe` call (aws-sdk).

But the `get subscription attributes` call on the other hand returns all the above fields as attributes although we did not define these 3 as attributes 🙂 Which makes it a particular case to handle I guess. If you deem it a decent solution; I can handle the `nil` case for the above mentioned 3 fields with the get attributes hook? This should resolve the issue IMO.

**Comment by mustafasencer** [comment]
@jaypipes Although the adoption issue is fixed. Now, the adoption test and the crud test have colliding subscription resources due to having the same bootstrap resources (because AWS returns the same **subscription arn** when the topic arn and the endpoint are the same). This causes issues when the adoption and crud test are performed in parallel.

What would be your recommended approach here to resolve this issue, the possible ways that comes my mind are:
- Create another bootstrap queue/topic for the adoption test?
- Enforce sequential execution for the tests present within the `test_subscription.py` file perhaps?

**Comment by RedbackThomson** [comment]
Nice. This is a great little fix. Appreciate it very much!
/lgtm

**Comment by RedbackThomson** [comment]
> Create another bootstrap queue/topic for the adoption test?

I think this would be the best option. These resources are fairly fast to bootstrap, so it's simple to just add more if they conflict.

**Comment by mustafasencer** [comment]
@RedbackThomson Thanks for the feedback, I added the additional bootstrap resource for the adoption test case [[here](https://github.com/aws-controllers-k8s/sns-controller/pull/38/commits/c026c356d615bfc9bc8d86830ec81e4b1a141083)].

**Pull request merged**
